default_platform(:ios)

platform :ios do
	desc "Lint lane"
	lane :lint do
		swiftlint(
			mode: :lint,      # SwiftLint mode: :lint (default) or :autocorrect
			executable: "Pods/SwiftLint/swiftlint",
			# reporter: "github-actions-logging",
			# output_file: "swiftlint.result.json", # The path of the output file (optional)
			raise_if_swiftlint_error: true     # Allow fastlane to raise an error if swiftlint fails
			# strict: true
			# ignore_exit_status: true    # Allow fastlane to continue even if SwiftLint returns a non-zero exit status
		)
	end

	desc "Install dependencies"
	lane :install_dependencies do
		cocoapods(
  		clean_install: true,
  		podfile: "./Podfile"
		)
	end
end
